insert into utilisateurs (id, email, password) values (2, 'lpont1@uiuc.edu', '123');
insert into utilisateurs (id, email, password) values (3, 'mmarchelli2@globo.com', '123');
insert into utilisateurs (id, email, password) values (4, 'kgrabiec3@dagondesign.com', '123');
insert into utilisateurs (id, email, password) values (5, 'fkennett4@freewebs.com', '123');
insert into utilisateurs (id, email, password) values (6, 'ecutbush5@reverbnation.com', '123');
insert into utilisateurs (id, email, password) values (7, 'mgarner6@disqus.com', '123');
insert into utilisateurs (id, email, password) values (8, 'blevermore7@psu.edu', '123');
insert into utilisateurs (id, email, password) values (9, 'fshilstone8@nationalgeographic.com', '123');
insert into utilisateurs (id, email, password) values (10, 'scarrell9@craigslist.org', '123');
